### ISSUE TITLE
text/html JSON content shown as text

### ISSUE THREAD

**Issue by totemcaf** [bhollis/jsonview#114]
I tried to use this plugin with some servers that report the JSON as "text/html; charset=utf-8" but the plugins never shows up. I tried the sample URL you provide and it worked.
I also configured in the "Alternate JSON content types" text box.
Any idea?

Thanks,
Carlos

**Comment by bhollis** [comment]
text/html is HTML, not JSON. It's also not one of the MIME types you can configure JSONView to use, because then every web page you visit would be interpreted as JSON. 

-Ben

**Comment by thevoiceless** [comment]
@bhollis Commenting here instead of opening a new issue: Would it be possible to add a menu item somewhere to request that JSONView try to process a page even if the mime type doesn't say it's JSON? Not as a persistent setting, but on an individual one-time basis. I have the same issue as the original poster; a client's API (which I have no control over) returns JSON with the wrong mime type. Currently I've resorted to copy/pasting into Sublime to auto-format...
