### ISSUE TITLE
Opening files with file:/// does not work

### ISSUE THREAD

**Issue by cardoe** [bhollis/jsonview#118]
I've currently got a file opened in a tab with the URL of `file:///Users/cardoe/recorded.json` and JSONView is not handling it. However when I look at the Page Info for the page I notice that Firefox believes the content type to be `text/plain` which is obviously not correct. However I notice that JSONview's code appears to imply that it will treat file extensions of .json as application/json.

**Comment by Trebly** [comment]
The same.
Unable to open a file:///<logicial disk>:/.......json file.
The file (15Mo) is opened as text.

**Comment by bhollis** [comment]
What happens if you disable, and then re-enable, the extension?

**Comment by Trebly** [comment]
Hi,

Doesn't change anything.

It is possible, as I said that the size of the file can be determinant
(15Mo and 40,000 items), but can be too something else.
It is a back-up of bookmarks of FF (an importation had failed (timeout
on script execution but confirm twenty times) - this three times. So I
have to look at the content to treat later this file by soft (to get
back the bookmarks and their folders), because Firefox is currently
quite unable to manage it (computing near 30 second at each operation).

I could view it with JSonEdit (local utility), I am sure that the
content is good.

May be if there is a limitation and may be or not any available work
around with the need of a confirmation about the time needed to load and
display for example, then a warning can tell either :
- file too large the limit is xMo and/or nodes
- or large file (size) confirm : the load time can be...

Best regards

Trebly

**Comment by davidelang** [comment]
do you get an error saying that the json couldn't be parsed?
most large files are not a single json object, they are a bunch of them, and json view can't handle that.
I had a similar case where the file consisted of multiple json objects
{json}
{json}
etc

I found that if I deleted all but the first object, jsonview was able to display it, so I changed my file to
[
{json},
{json},
{json}
]
and jsonview was able to display it.

**Comment by Trebly** [comment]
Hi,

Sorry, I got problems with notifications. I just review today everything.

What was happening is that the json file was simply loaded as text, as if the extension was not active at all.

Currently I uses now an external independent tool and have not tested again

Best regards

**Comment by bhollis** [comment]
I'm unable to reproduce that:

![jsonview-file](https://cloud.githubusercontent.com/assets/313208/21958345/44bc9950-da61-11e6-9122-b365c4c40566.gif)
