### ISSUE TITLE
ZERO WIDTH SPACE (U+200B) characters in copied data

### ISSUE THREAD

**Issue by lassus** [bhollis/jsonview#129]
While copying json from browser a zero width space character is added in front of integers.

when formatted json _free: 123_ is copied the string in copy-buffer is _"free": <200b>123_

U+200B is not a Whitespace [WS] caharacter and thus it isn't allowed between tokens.

**Comment by bhollis** [comment]
Uh oh. This came from a PR I got a bit ago, and I didn't check all the use
cases well enough before accepting it. I'll get this fixed.

**Comment by Bartvds** [comment]
I hope you can roll out a fix soon, because this issue makes using this plugin unreliable and outright dangerous.

Most input validation in CMS's and forms will catch it, but IDE's wont: like Pycharm will accept this character so if your app had bunch of these values hardcoded (like in a config) then you are in for a fun debugging session (not really). 

We had some as keys in a python dictionary that of course never map to the real integer value. We only discovered the real issue after someones scrappy non-Unicode Windows shell crashed while print()-ing during debugging.

**Comment by bhollis** [comment]
I'll be rolling back the change that caused this sometime this weekend.
