### ISSUE TITLE
Support Firefox multiprocess (electrolysis, e10s)

### ISSUE THREAD

**Issue by bhollis** [bhollis/jsonview#97]
See [Mozilla bug 1099976](https://bugzilla.mozilla.org/show_bug.cgi?id=1099976). JSONView needs to be updated to support Firefox's long-awaited multiprocess mode.

[Developer info for dealing with multiprocess in addons](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox).

**Comment by canuckistani** [comment]
Frustrating - building from HEAD in github just fails silently with no errors. :(

**Comment by bhollis** [comment]
Building JSONView? On what kind of system?

**Comment by canuckistani** [comment]
@bhollis sorry - on OS X, I built an xpi after making some changes to the codebase to support [jpm](https://github.com/mozilla/jpm). The xpi built fine in and works correctly without e10s enabled, but fails silently when e10s is enabled. It's too bad we ( Firefox ) don't provide some sort of error.

I talked to Honza ( Firebug ) about this and he related that it is probably due to the xpcom service being run in the parent process and not in a framescript in a child process. I think he's going to reach out to you and provide more detailed feedback.

**Comment by bhollis** [comment]
Thanks that'd be helpful. It looks like we still use cfx to build (it's in the README).

**Comment by janodvarko** [comment]
I have just sent PR that fixes the support for e10s 
https://github.com/bhollis/jsonview/pull/99

Needs testing now.

(btw. I also had some troubles building using cfx, see the PR comment)

Honza

**Comment by bhollis** [comment]
Awesome, thanks for tackling this. I'll close this issue in favor of the PR, where we can track getting the final issues ironed out.
